-- Schema para LEK BANK (Supabase)
create table if not exists public.loans (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  name text not null,
  phone text,
  principal numeric(12,2) not null,
  annual_rate numeric(6,4) default 0,
  months int not null,
  start_date date,
  created_at timestamptz default now()
);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  loan_id bigint references public.loans(id) on delete cascade,
  index int not null,
  paid_at timestamptz default now()
);

create index if not exists loans_user_id_idx on public.loans (user_id);
create index if not exists payments_loan_id_idx on public.payments (loan_id);
